DjangoWebDev/IngotCRM/ingotcrm/ecom/urls.py
from django.urls import path
from . import views


app_name = 'ecom'

urlpatterns = [
    path('order_page/<int:id>/<str:level_name>', views.orderPage, name='order_page'),
    path('paypal_return/', views.paypal_return, name='paypal-return'),
    path('paypal_cancel/', views.paypal_cancel, name='paypal-cancel'),
    path('order_complete/', views.orderCompletePage, name='order_complete'),
    path('order_incomplete/', views.orderIncompletePage, name='order_incomplete'),
]

DjangoWebDev/IngotCRM/ingotcrm/ingotcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import (
    LandingPageView, AboutPageView, 
    PricingPageView,  SignupView, 
    CustomLoginView, CustomPasswordChangeView, 
    CustomPasswordResetView, CustomPasswordResetConfirmView,
    DonateView, 
)

from django.conf import settings
from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView,
    PasswordChangeDoneView
    )
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="landing-page"),
    path('about/', AboutPageView.as_view(), name="about-page"),
    path('pricing/', PricingPageView.as_view(), name="pricing-page"),
    path('leads/', include('leads.urls', namespace="leads")),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', SignupView.as_view(), name='register'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password-reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('agents/', include('agents.urls', namespace='agents')),
    path('change_password/', CustomPasswordChangeView.as_view(), name='change_password'),
    path('password_change_done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('donate/', DonateView, name='donate'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('ecom/', include('ecom.urls')),
]

handler404 = 'leads.views.Error404View'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoWebDev/IngotCRM/ingotcrm/leads/urls.py
from django.urls import path
from .views import (
    LeadDeleteView,
    LeadListView,
    LeadDetailView,
    LeadCreateView,
    LeadUpdateView,
    AssignAgentView,
    CategoryListView,
    CategoryDetailView,
    LeadCategoryUpdateView,
    DocumentListView,
    DocumentDetailView,
    DocumentUploadView,
    DocumentUpdateView,
    DocumentDeleteView,
    )

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign_agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('documents/', DocumentListView.as_view(), name='document-list'),
    path('documents/<int:pk>/', DocumentDetailView.as_view(), name='document-detail'),
    path('upload_document/', DocumentUploadView.as_view(), name='document-upload'),
    path('documents/<int:pk>/update/', DocumentUpdateView.as_view(), name='document-update'),
    path('documents/<int:pk>/delete/', DocumentDeleteView.as_view(), name='document-delete'),
]

DjangoWebDev/IngotCRM/ingotcrm/ecom/models.py
from django.db import models

# Create your models here.

class Order(models.Model):
    pass

DjangoWebDev/IngotCRM/ingotcrm/ecom/views.py
import uuid

from django.urls import reverse
from django.contrib import messages
from django.conf import settings
from django.shortcuts import render, redirect
from paypal.standard.forms import PayPalPaymentsForm

from leads.models import User


def orderPage(request, id, level_name):
    org = User.objects.get(id=id)
    host = request.get_host()
    level_name = level_name

    if level_name == "silver":
        price='24.99'
        team_size = 20
    elif level_name == "gold":
        price='49.99'
        team_size = 50

    paypal_dict = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': price,
        'item_name': f'Order {org}',
        'invoice': str(uuid.uuid4()),
        'currency_code': 'USD',
        'notify_url': f'http://{host}{reverse("paypal-ipn")}',
        'return_url': f'http://{host}{reverse("ecom:paypal-return")}',
        'cancel_return': f'http://{host}{reverse("ecom:paypal-cancel")}',
    }
    form = PayPalPaymentsForm(initial=paypal_dict)
    context = {'user': org, 'form': form,
               'level_name': level_name.capitalize(), 'price': price}
    return render(request, 'order_page.html', context)


def paypal_return(request, **kwargs):
    return redirect('ecom:order_complete')


def paypal_cancel(request):
    messages.error(request, 'Your order has been cancelled!')
    return redirect('ecom:order_incomplete')


def orderCompletePage(request, **kwargs):
    return render(request, 'order_complete.html', context={})

def orderIncompletePage(request):
    return render(request, 'order_incomplete.html', {})

DjangoWebDev/IngotCRM/ingotcrm/ecom/templates/order_complete.html
{% extends "base.html" %}

{% block content %}
<section class="py-12 xl:py-24">
    <div>
        <h1 class="block sm:text-4xl text-2xl font-extrabold mb-1 mt-5 text-center text-black dark:text-white">
            Order was <span class="text-green-800 dark:text-green-400">successfully</span> operated! Thanks for choosing our service's!
        </h1>
        <br/>
        <br/>
        <p class="text-xl font-semibold mb-1 mt-5 text-center text-black dark:text-white">
            <a href="{% url 'leads:lead-list' %}">Go to the Leads list page ...</a>
        </p>
        <br/>
    </div>
</section>
{% endblock content %}

DjangoWebDev/IngotCRM/ingotcrm/ecom/templates/order_incomplete.html
{% extends "base.html" %}

{% block content %}
<section class="py-12 xl:py-24">
    <div>
        <h1 class="block sm:text-4xl text-2xl font-extrabold mb-1 mt-5 text-center text-black dark:text-white">
            Order was <span class="text-red-800 dark:text-red-400">failed</span>! Try again later...
        </h1>
        <br/>
        <br/>
        <p class="text-xl font-semibold mb-1 mt-5 text-center text-black dark:text-white">
            <a href="{% url 'leads:lead-list' %}">Go to the Leads list page ...</a>
        </p>
        <br/>
    </div>
</section>
{% endblock content %}

DjangoWebDev/IngotCRM/ingotcrm/ecom/templates/order_page.html
{% extends "base.html" %}

{% block content %}
<section class="py-12 xl:py-24">
    <div>
        <h1 class="block sm:text-3xl text-2xl font-extrabold mb-1 mt-5 text-center text-black dark:text-white">
            You can buy the '{{level_name}}' subscription for only {{price}}$ right now
        </h1>
        <br/>
        {% comment %} {% if messages %}
            <ul class="messages">
            {% for message in messages %}
                <li class="text-center font-semibold uppercase text-black dark:text-white">
                    {{message}}
                </li>
            {% endfor %}
            </ul>
        
        {% endif %} {% endcomment %}
        <br/>
        <hr/>
    </div>

    <div class="flex max-w-lg mx-auto justify-center align-center mt-12 p-6 bg-[#FCF1F1] border border-gray-200 rounded-lg shadow dark:bg-[#474E68] dark:border-gray-800">
        {{ form.render }}
    </div>
</section>
{% endblock content %}