DjangoWebDev/IngotCRM/ingotcrm/agents/urls.py
from django.urls import path
from .views import (AgentListView, AgentCreateView, AgentDetailView, 
                AgentDeleteView, AgentUpdateView, AgentProfileView, 
                AgentProfileUpdateView, )


app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/profile/', AgentProfileView.as_view(), name='agent-profile'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/profile/update/', AgentProfileUpdateView.as_view(), name='profile-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
]

DjangoWebDev/IngotCRM/ingotcrm/ecom/urls.py
from django.urls import path
from . import views


app_name = 'ecom'

urlpatterns = [
    path('order_page/<int:id>/<str:level_name>', views.orderPage, name='order_page'),
    path('paypal_return/', views.paypal_return, name='paypal-return'),
    path('paypal_cancel/', views.paypal_cancel, name='paypal-cancel'),
    path('order_complete/', views.orderCompletePage, name='order_complete'),
    path('order_incomplete/', views.orderIncompletePage, name='order_incomplete'),
]

DjangoWebDev/IngotCRM/ingotcrm/ingotcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import (
    LandingPageView, AboutPageView, 
    PricingPageView,  SignupView, 
    CustomLoginView, CustomPasswordChangeView, 
    CustomPasswordResetView, CustomPasswordResetConfirmView,
    DonateView, 
)

from django.conf import settings
from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView,
    PasswordChangeDoneView
    )
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="landing-page"),
    path('about/', AboutPageView.as_view(), name="about-page"),
    path('pricing/', PricingPageView.as_view(), name="pricing-page"),
    path('leads/', include('leads.urls', namespace="leads")),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', SignupView.as_view(), name='register'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password-reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('agents/', include('agents.urls', namespace='agents')),
    path('change_password/', CustomPasswordChangeView.as_view(), name='change_password'),
    path('password_change_done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('donate/', DonateView, name='donate'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('ecom/', include('ecom.urls')),
]

handler404 = 'leads.views.Error404View'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoWebDev/IngotCRM/ingotcrm/agents/models.py
from django.db import models

# Create your models here.

DjangoWebDev/IngotCRM/ingotcrm/leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver

# For file upload validator
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError


class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)
    position = models.CharField(max_length=100, default="employee", null=True, blank=True)
    phone_number = models.CharField(max_length=100, default="unknown", null=True, blank=True)
    photo = models.ImageField(verbose_name="Photo", null=True, blank=True, upload_to="images/agents")


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


# class Rights(models.Model):
#     organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

#     level = models.CharField(default="free", max_length=100)
#     team_size = models.IntegerField(default=5)
#     individual_configuration = models.BooleanField(default=False)
#     premium_support = models.DateTimeField(auto_now_add=True)
#     price = models.FloatField(default=00.00, max_length=100)

#     def __str__(self):
#         return f"{self.level}"


# class Order(models.Model):
#     rights = models.ForeignKey(Rights, on_delete=models.CASCADE)

#     def __str__(self):
#         return f"{self.rights.level}, {self.rights.organisation}"


class Lead(models.Model):
    first_name = models.CharField(max_length=28)
    last_name = models.CharField(max_length=28)
    age = models.IntegerField(default=0)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20, unique=True)
    email = models.EmailField(unique=True)
    photo = models.ImageField(verbose_name="Photo", null=True, blank=True, upload_to="images/leads")

    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)    # Every lead has an agent
    category = models.ForeignKey("Category", related_name="lead_cat", null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)             # Agent == User(AbstractUser)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE) # Organisation == UserProfile == User(AbstractUser)

    def __str__(self):
        return self.user.email


class Category(models.Model):
    name = models.CharField(max_length=50)
    organisation = models.ForeignKey(UserProfile, on_delete = models.CASCADE)

    def __str__(self):
        return self.name
        

class Document(models.Model):
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    is_secret = models.BooleanField(default=False)
    file = models.FileField(validators=FileExtensionValidator( ['pdf', 'txt', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'] ), null=False, blank=False, upload_to="media/")
    date_added = models.DateTimeField(auto_now_add=True)

    lead = models.ForeignKey("Lead", null=False, blank=False, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)


class LeadComment(models.Model):
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    lead = models.ForeignKey("Lead", null=False, blank=False, related_name="lead_com", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.lead.email} - {self.author.username}"


def postUserCreatedSignal(sender, instance, created, **kwargs):
    if created:
        user = UserProfile.objects.create(user=instance)

post_save.connect(postUserCreatedSignal, sender=User)


@receiver(post_save, sender=UserProfile)
def create_categories(sender, instance, created, **kwargs):
    if created:
        category_names = ['Unassigned', 'Contacted', 'Converted', 'Unconverted']
        for name in category_names:
            Category.objects.create(name=name, organisation=instance)

DjangoWebDev/IngotCRM/ingotcrm/agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from leads.models import Agent, User
from crispy_forms.helper import FormHelper


USER = get_user_model()


class AgentCreateModelForm(forms.ModelForm):
    class Meta:
        model = USER
        fields = (
            'username',
            'first_name',
            'last_name',
            'phone_number',
            'position',
            'photo',
            'email',
        )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False

        self.fields['photo'].label = 'Profile photo'
        self.fields["username"].help_text = ''


# class AgentUpdateModelForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = (
#             'username',
#             'first_name',
#             'last_name',
#             'position',
#             'email',
#         )
    
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
        
#         self.helper = FormHelper(self)
#         self.helper.form_show_labels = False

#         self.fields['username'].help_text = ""
#         self.fields['first_name'].label = ""
#         self.fields['last_name'].label = ""


class AgentProfileUpdateModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'phone_number',
            'photo',
        )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False
        
        self.fields['photo'].label = 'Profile photo'


class CustomAgentUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "username", 
            "first_name", 
            "last_name", 
            "position", 
            "photo",
            "email",
        )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False
        
        self.fields['photo'].label = 'Profile photo'
        self.fields["username"].help_text = ''

DjangoWebDev/IngotCRM/ingotcrm/leads/forms.py
from typing import Any, Dict, Mapping, Optional, Type, Union
from django import forms
from crispy_forms.helper import FormHelper
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList

from django.contrib.auth.forms import (
    UserCreationForm, UsernameField, AuthenticationForm, 
    PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)

from .models import Lead, User, Agent, Document, Category, LeadComment


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'description',
            'phone_number',
            'email',
            'photo',
            'category',
            'agent',
        )

    def __init__(self, *args, **kwargs):
        organisation = kwargs.pop('organisation', None)
        super().__init__(*args, **kwargs)
        
        if organisation:
            categories = Category.objects.filter(organisation=organisation)
            self.fields['category'].queryset = categories
            
            agents = Agent.objects.filter(organisation=organisation)
            self.fields['agent'].queryset = agents
        
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False
        #self.helper.label_class = "text-black dark:text-white bg-yellow-500"
        self.fields['photo'].label = 'Profile photo'


class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", )
        field_classes = {"username": UsernameField, }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
      
        self.helper = FormHelper(self)

        self.helper.form_show_labels = False

        self.fields["username"].help_text = ''
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ("username", )
        field_classes = {"username": UsernameField, }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
      
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False


class CustomPasswordChangeForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ("old_password", "new_password1", "new_password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False

        self.fields['old_password'].help_text = ''
        self.fields['old_password'].label = ''
        self.fields['new_password1'].help_text = ''
        self.fields['new_password1'].label = ''
        self.fields['new_password2'].help_text = ''
        self.fields['new_password2'].label = ''


class CustomPasswordResetForm(PasswordResetForm):
    class Meta:
        model = User
        fields = ("email", )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_show_labels = False


class CustomSetPasswordForm(SetPasswordForm):
    class Meta:
        model = User
        fields = ("new_password1", "new_password2")
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_show_labels = False

        self.fields["new_password1"].help_text = ''


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organisation=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'category',
        )
    
    def __init__(self, *args, **kwargs):
        organisation = kwargs.pop('organisation', None)
        super().__init__(*args, **kwargs)
        
        if organisation:
            categories = Category.objects.filter(organisation=organisation)
            self.fields['category'].queryset = categories
        
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False


class UploadDocumentModelForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = (
            'lead',
            'title',
            'description',
            'is_secret',
            'file',
            )

    def __init__(self, *args, **kwargs):
        organisation = kwargs.pop('organisation', None)
        super().__init__(*args, **kwargs)
        
        if organisation:
            leads = Lead.objects.filter(organisation=organisation)
            self.fields['leads'].queryset = leads
        
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False
        self.fields['file'].label = 'File'
        self.fields['file'].help_text = ''


class LeadCommentForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={
        "class": "md-textarea form-control",
        "placeholder": "Write your comment here...",
        "rows": '4',
        }))
    text.label = ""

    class Meta:
        model = LeadComment
        fields = [
            "text",
        ]

DjangoWebDev/IngotCRM/ingotcrm/agents/templates/agents/agent_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
  <h1 class="sm:text-3xl text-2xl font-extrabold mb-1 mt-5 text-center text-black dark:text-white border-b-2 border-gray-200 dark:border-green-200">Create a new agent</h1>
  <br/>

  <div class="flex justify-center text-center mt-10 px-2">
    <form method="post" enctype="multipart/form-data" autocomplete="off">
      {% csrf_token %}
      <div class="grid grid-cols-4 gap-4 w-full py-4 bg-gray-200 border border-gray-200 rounded-lg shadow dark:bg-[#474E68] dark:border-gray-800">
        <div class="col-span-4 px-2">
          <label for="id_username" class="text-black dark:text-white">Username</label>
          {{ form.username|as_crispy_field }}
        </div>
        <div class="col-span-2 px-2">
          <label for="id_firstname" class="text-black dark:text-white">First name</label>
          {{ form.first_name|as_crispy_field }}
        </div>
        <div class="col-span-2 px-2">
          <label for="id_lastname" class="text-black dark:text-white">Last name</label>
          {{ form.last_name|as_crispy_field }}
        </div>
        <div class="col-span-4 px-2">
          <label for="id_email" class="text-black dark:text-white">Email</label>
          {{ form.email|as_crispy_field }}
        </div>
        <div class="col-span-2 px-2">
          <label for="id_phonenumber" class="text-black dark:text-white">Phone number</label>
          {{ form.phone_number|as_crispy_field }}
        </div>
        <div class="col-span-2 px-2">
          <label for="id_position" class="text-black dark:text-white">Position</label>
          {{ form.position|as_crispy_field }}
        </div>
        <div class="col-start-2 col-end-4 px-4">
          <label for="id_photo" class="text-black dark:text-white">Profile photo</label>
          {{ form.photo|as_crispy_field }}
        </div>

        <p class="col-start-2 col-end-4">
          <button type="submit" class="relative inline-flex items-center justify-center p-0.5 mt-4 overflow-hidden text-xl text-bold font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-red-200 via-red-300 to-yellow-200 group-hover:from-red-200 group-hover:via-red-300 group-hover:to-yellow-200 dark:bg-gradient-to-br dark:from-green-400 dark:to-blue-600 dark:group-hover:from-green-400 dark:group-hover:to-blue-600 dark:hover:text-white hover:text-black dark:text-white focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800">
            <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-gray-200 dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                Create
            </span>
          </button>
        </p>
      </div>
      <br/>
    </form>
  </div>
{% endblock content %}

DjangoWebDev/IngotCRM/ingotcrm/agents/templates/agents/agent_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<section class="bg-[#FCF1F1] dark:bg-[#474E68] text-gray-600 body-font py-8 h-full">
  <div class="container px-5 mx-auto py-12 flex juxtify-center">
    <div class="lg:w-4/6 mx-auto">
      <div class="flex flex-col sm:flex-row mt-10">
        <div class="sm:w-1/3 text-center sm:pr-8 sm:py-8">
          <div class="w-20 h-20 rounded-full inline-flex items-center justify-center bg-gray-200 text-black dark:text-white">

              {% if agent.user.photo %}
                <img src="{{ agent.user.photo.url }}" alt="Profile picture" style="width: 150px; height: 150px; border-radius: 50%;">
              {% else %}
                <img src="{% static 'images/UserPhoto.jpg' %}" alt="Profile picture" style="width: 150px; height: 150px; border-radius: 50%;">
              {% endif %}
          </div>
          <div class="flex flex-col items-center text-center justify-center">
            <h2 class="font-medium title-font mt-4 text-black dark:text-white text-lg">{{ agent.user.username }}</h2>
            <div class="w-12 h-1 bg-green-500 rounded mt-2 mb-3"></div>
            <p class="text-base text-black dark:text-white">
              {{ agent.user.position }}
            </p>
          </div>
        </div>
        <div class="sm:w-2/3 sm:pl-8 sm:py-8 sm:border-l text-black dark:text-white border-gray-200 dark:border-green-200 sm:border-t-0 border-t mt-4 pt-4 sm:mt-0 text-center sm:text-left">
          <p class="mr-4 leading-relaxed text-lg font-medium mb-2">
            <button id="toggle-information-btn">Information</button>
            <div class="border-2 border-gray-200 dark:border-green-200 drop-shadow-xl"/>
            </div>
          </p>
          <div id="paragraphs" class="sm:w-2/3 sm:pl-8 ml-2 text-xm text-black dark:text-white">
            <p><em>Full name</em>: {{ agent.user.first_name }} {{ agent.user.last_name }}</p>
            <p><em>Phone number</em>:
              <button id="phone_button" class="underline" onclick="copyPhoneToClipboard()">
                {{ agent.user.phone_number }}
              </button>
              <div id="copyAlertPhone" class="flex ml-4 px-2 text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
                <div class="text-sm font-small">
                  The phone number was copied successfully.
                </div>
              </div>
            </p>
            <p><em>Email</em>:
              <button id="email_button" class="underline" onclick="copyEmailToClipboard()">
                {{ agent.user.email }}
              </button>
              <div id="copyAlertEmail" class="flex ml-4 pr-2 text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
                <div class="ml-3 text-sm font-small">
                  The email was copied successfully.
                </div>
              </div>
            </p>
            <br/><br/>
          </div>
          <p class="text-green-500 inline-flex items-center mt-8">
            <a href="{% url 'agents:agent-update' agent.id %}"><button class="flex mx-auto ml-8 text-white bg-green-500 border-0 py-2 px-8 focus:outline-none hover:bg-green-600 rounded text-lg align-center" style="display: block; float: left;"> Update </button></a>
            <a href="{% url 'agents:agent-delete' agent.id %}"><button class="flex mx-auto text-white bg-gray-500 border-0 py-2 px-8 focus:outline-none hover:bg-red-600 rounded text-lg align-center" style="display: block; float: left; margin-left: 20px;"> Delete </button></a>
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}


{% block head %}
  <style>
    #copyAlertEmail {
      display: none;
    }

    #copyAlertPhone {
      display: none;
    }
  </style>
{% endblock head %}


{% block js %}
  <script>
		$(document).ready(function(){
			$('#toggle-information-btn').click(function(){
				$('#paragraphs').toggle();
				if ($(this).text() === 'Information') {
					$(this).text('Show the information');
				} else if ($(this).text() === 'Show the information') {
					$(this).text('Information');
				};
			});
		});

    $(document).ready(function(){
			$('#email_button').click(function(){
				$('#copyAlertEmail').show();
			});
		});

    function copyEmailToClipboard() {
      var emailButton = document.getElementById("email_button");
      var tempInput = document.createElement("input");

      tempInput.value = emailButton.innerText;
      document.body.appendChild(tempInput);
      tempInput.select();
      document.execCommand("copy");
      document.body.removeChild(tempInput);

      var myElement = document.getElementById('copyAlertEmail');
      myElement.style.display = 'block';

      setTimeout(function() {
        myElement.style.display = 'none';
      }, 2000);
    }
        
		$(document).ready(function(){
			$('#phone_button').click(function(){
				$('#copyAlertPhone').show();
			});
		});

    function copyPhoneToClipboard() {
      var emailButton = document.getElementById("phone_button");
      var tempInput = document.createElement("input");
      
      tempInput.value = emailButton.innerText;
      document.body.appendChild(tempInput);
      tempInput.select();
      document.execCommand("copy");
      document.body.removeChild(tempInput);

      var myElement = document.getElementById('copyAlertPhone');
      myElement.style.display = 'block';

      setTimeout(function() {
        myElement.style.display = 'none';
      }, 2000);
    }
  </script>

{% endblock js %}

DjangoWebDev/IngotCRM/ingotcrm/agents/templates/agents/agent_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
  <h1 class="sm:text-3xl text-2xl font-extrabold mb-1 mt-5 text-center text-black dark:text-white border-b-2 border-gray-200 dark:border-green-200">
    Update the '<a href="{% url 'agents:agent-detail' agent.pk %}" class="text-gray-700 dark:text-green-200 hover:text-cyan-600 dark:hover:text-cyan-400 hover:underline">{{ agent.user.first_name }} {{ agent.user.last_name }}</a>' agent
  </h1>

  <div class="flex justify-center text-center mt-6 px-2">
    <form method="post" enctype="multipart/form-data" autocomplete="off">
      {% csrf_token %}
      <div class="grid grid-cols-4 gap-4 w-full py-4 bg-gray-200 border border-gray-200 rounded-lg shadow dark:bg-[#474E68] dark:border-gray-800 text-black dark:text-white">
        <div class="col-span-4 px-2">
          <label for="id_username" class="text-black dark:text-white">Username</label>
          {{ form.username|as_crispy_field }}
        </div>
        <div class="col-span-2 px-2">
          <label for="id_first_name" class="text-black dark:text-white">First name</label>
          {{ form.first_name|as_crispy_field }}
        </div>
        <div class="col-span-2 px-2">
          <label for="id_last_name" class="text-black dark:text-white">Last name</label>
          {{ form.last_name|as_crispy_field }}
        </div>
        <div class="col-span-4 px-2">
          <label for="id_email" class="text-black dark:text-white">Email</label>
          {{ form.email|as_crispy_field }}
        </div>
        <div class="col-span-4 px-2">
          <label for="id_position" class="text-black dark:text-white">Position</label>
          {{ form.position|as_crispy_field }}
        </div>

        <p class="col-start-2 col-end-4 px-2 pb-4">
          <button type="submit" class="relative inline-flex items-center justify-center p-0.5 mt-4 overflow-hidden text-xl text-bold font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-red-200 via-red-300 to-yellow-200 group-hover:from-red-200 group-hover:via-red-300 group-hover:to-yellow-200 dark:bg-gradient-to-br dark:from-green-400 dark:to-blue-600 dark:group-hover:from-green-400 dark:group-hover:to-blue-600 dark:hover:text-white hover:text-black dark:text-white focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800">
            <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                Update
            </span>
          </button>
        </p>
      </div>
      <br/>
    </form>
  </div>
{% endblock content %}