DjangoWebDev/IngotCRM/ingotcrm/agents/urls.py
from django.urls import path
from .views import (AgentListView, AgentCreateView, AgentDetailView, 
                AgentDeleteView, AgentUpdateView, AgentProfileView, 
                AgentProfileUpdateView, )


app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/profile/', AgentProfileView.as_view(), name='agent-profile'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/profile/update/', AgentProfileUpdateView.as_view(), name='profile-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
]

DjangoWebDev/IngotCRM/ingotcrm/ecom/urls.py
from django.urls import path
from . import views


app_name = 'ecom'

urlpatterns = [
    path('order_page/<int:id>/<str:level_name>', views.orderPage, name='order_page'),
    path('paypal_return/', views.paypal_return, name='paypal-return'),
    path('paypal_cancel/', views.paypal_cancel, name='paypal-cancel'),
    path('order_complete/', views.orderCompletePage, name='order_complete'),
    path('order_incomplete/', views.orderIncompletePage, name='order_incomplete'),
]

DjangoWebDev/IngotCRM/ingotcrm/ingotcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import (
    LandingPageView, AboutPageView, 
    PricingPageView,  SignupView, 
    CustomLoginView, CustomPasswordChangeView, 
    CustomPasswordResetView, CustomPasswordResetConfirmView,
    DonateView, 
)

from django.conf import settings
from django.contrib.auth.views import (
    LogoutView, 
    PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView,
    PasswordChangeDoneView
    )
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="landing-page"),
    path('about/', AboutPageView.as_view(), name="about-page"),
    path('pricing/', PricingPageView.as_view(), name="pricing-page"),
    path('leads/', include('leads.urls', namespace="leads")),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', SignupView.as_view(), name='register'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password-reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('agents/', include('agents.urls', namespace='agents')),
    path('change_password/', CustomPasswordChangeView.as_view(), name='change_password'),
    path('password_change_done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('donate/', DonateView, name='donate'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('ecom/', include('ecom.urls')),
]

handler404 = 'leads.views.Error404View'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoWebDev/IngotCRM/ingotcrm/leads/urls.py
from django.urls import path
from .views import (
    LeadDeleteView,
    LeadListView,
    LeadDetailView,
    LeadCreateView,
    LeadUpdateView,
    AssignAgentView,
    CategoryListView,
    CategoryDetailView,
    LeadCategoryUpdateView,
    DocumentListView,
    DocumentDetailView,
    DocumentUploadView,
    DocumentUpdateView,
    DocumentDeleteView,
    )

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign_agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('documents/', DocumentListView.as_view(), name='document-list'),
    path('documents/<int:pk>/', DocumentDetailView.as_view(), name='document-detail'),
    path('upload_document/', DocumentUploadView.as_view(), name='document-upload'),
    path('documents/<int:pk>/update/', DocumentUpdateView.as_view(), name='document-update'),
    path('documents/<int:pk>/delete/', DocumentDeleteView.as_view(), name='document-delete'),
]

DjangoWebDev/IngotCRM/ingotcrm/leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver

# For file upload validator
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError


class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)
    position = models.CharField(max_length=100, default="employee", null=True, blank=True)
    phone_number = models.CharField(max_length=100, default="unknown", null=True, blank=True)
    photo = models.ImageField(verbose_name="Photo", null=True, blank=True, upload_to="images/agents")


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


# class Rights(models.Model):
#     organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

#     level = models.CharField(default="free", max_length=100)
#     team_size = models.IntegerField(default=5)
#     individual_configuration = models.BooleanField(default=False)
#     premium_support = models.DateTimeField(auto_now_add=True)
#     price = models.FloatField(default=00.00, max_length=100)

#     def __str__(self):
#         return f"{self.level}"


# class Order(models.Model):
#     rights = models.ForeignKey(Rights, on_delete=models.CASCADE)

#     def __str__(self):
#         return f"{self.rights.level}, {self.rights.organisation}"


class Lead(models.Model):
    first_name = models.CharField(max_length=28)
    last_name = models.CharField(max_length=28)
    age = models.IntegerField(default=0)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20, unique=True)
    email = models.EmailField(unique=True)
    photo = models.ImageField(verbose_name="Photo", null=True, blank=True, upload_to="images/leads")

    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)    # Every lead has an agent
    category = models.ForeignKey("Category", related_name="lead_cat", null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)             # Agent == User(AbstractUser)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE) # Organisation == UserProfile == User(AbstractUser)

    def __str__(self):
        return self.user.email


class Category(models.Model):
    name = models.CharField(max_length=50)
    organisation = models.ForeignKey(UserProfile, on_delete = models.CASCADE)

    def __str__(self):
        return self.name
        

class Document(models.Model):
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    is_secret = models.BooleanField(default=False)
    file = models.FileField(validators=FileExtensionValidator( ['pdf', 'txt', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'] ), null=False, blank=False, upload_to="media/")
    date_added = models.DateTimeField(auto_now_add=True)

    lead = models.ForeignKey("Lead", null=False, blank=False, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)


class LeadComment(models.Model):
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    lead = models.ForeignKey("Lead", null=False, blank=False, related_name="lead_com", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.lead.email} - {self.author.username}"


def postUserCreatedSignal(sender, instance, created, **kwargs):
    if created:
        user = UserProfile.objects.create(user=instance)

post_save.connect(postUserCreatedSignal, sender=User)


@receiver(post_save, sender=UserProfile)
def create_categories(sender, instance, created, **kwargs):
    if created:
        category_names = ['Unassigned', 'Contacted', 'Converted', 'Unconverted']
        for name in category_names:
            Category.objects.create(name=name, organisation=instance)

DjangoWebDev/IngotCRM/ingotcrm/templates/assign_agent.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
  <h1 class="sm:text-3xl text-2xl font-extrabold mb-1 mt-5 text-center text-black dark:text-white border-b-2 border-gray-200 dark:border-green-200">Assign an agent to this lead</h1>
  <br/>

  <div class="m-0 ml-auto mr-auto mt-2">
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="flex mx-auto mt-6 mb-6 text-white bg-green-500 border-0 px-8 focus:outline-none hover:bg-cyan-500 hover:text-black rounded text-lg">Submit</button>
      <br/>
    </form>
  </div>
{% endblock content %}

DjangoWebDev/IngotCRM/ingotcrm/templates/category_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="py-12 h-full bg-[#FCF1F1] dark:bg-[#474E68]">
  <div class="flex justify-center mt-5">
    <p class="text-5xl text-extrabold mr-5 mt-5 text-black dark:text-white">{{ category.name }}</p>
  </div>

  <div class="flex ml-5 mt-5 space-x-2 justify-left border-b-2 border-gray-200 dark:border-green-200 pb-2">
    <div class="flex">
      <a  href="{% url 'leads:category-list' %}"><button type="button" class="inline-block px-6 pt-2 mt-6 pb-2 bg-yellow-200 text-black font-medium text-xs leading-normal uppercase rounded shadow-md hover:bg-blue-300 hover:shadow-lg focus:bg-blue-300 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-300 active:shadow-lg transition duration-150 ease-in-out flex align-center">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-3 pb-1">
              <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
          </svg>
          Back to categories
      </button></a>
    </div>
  </div>

  <ul role="list" class="p-6 divide-y divide-slate-200">
  {% if category.lead_cat.all %}
    {% for lead in category.lead_cat.all %}
      <a href="{% url 'leads:lead-detail' lead.pk %}">
        <li class="flex pb-5 pt-5 ml-5 py-4 first:pt-0 last:pb-0 hover:border-l-2 hover:border-blue-300 mb-3 px-5">
            {% if lead.photo %}
              <img src="{{ lead.photo.url }}" alt="{% static 'images\UserPhoto.jpg' %}" class="h-12 w-12" style="border-radius: 50%;"/>
            {% else %}
              <img src="{% static 'images\UserPhoto.jpg' %}" alt="Photo" class="h-12 w-12" style="border-radius: 50%;"/>
            {% endif %}
          
          <div class="ml-3 overflow-hidden">
            <p class="text-sm font-medium text-black dark:text-white">
              
                <h3>{{ lead.first_name }} {{ lead.last_name }}</h3><h5 class="mr-9 text-gray-400"><h5>
              
            </p>
            <p class="text-sm truncate text-black dark:text-white">{{ lead.email }}</p>
          </div>
        </li>
      </a>
    {% endfor %}
  {% else %}
    <p class="text-sm font-medium text-black dark:text-white border-0"><h3>No matches</h3><h5 class="mr-9 text-gray-400"><h5></p>
  {% endif %}
</div>
    
{% endblock content %}

DjangoWebDev/IngotCRM/ingotcrm/templates/document_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="py-12 h-full bg-[#FCF1F1] dark:bg-[#474E68] px-2">
        <div class="flex justify-center">
            <p class="text-5xl text-extrabold mr-5 text-black dark:text-white">{{ document.title }}</p>
        </div>

        <div class="flex space-x-2 justify-left border-b-2 border-gray-200 dark:border-green-200 pb-4">
            <div>
                <a  href="{% url 'leads:document-list' %}"><button type="button" class="inline-block px-6 pt-2 pb-2 bg-yellow-200 text-black font-medium text-xs leading-normal uppercase rounded shadow-md hover:bg-blue-300 hover:shadow-lg focus:bg-blue-300 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-300 active:shadow-lg transition duration-150 ease-in-out flex align-center">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mr-3 pb-1">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
                    </svg>
                    Back to documents
                </button></a>
            </div>
        </div>

        <div class="flex mx-auto justify-center">
            <div class="sm:w-2/3 sm:pl-8 sm:py-8 mt-4 pt-4 sm:mt-0 text-center sm:text-left">
                <p class="mr-4 leading-relaxed text-lg font-medium mb-2">
                    <div class="sm:w-2/3 sm:pl-8 ml-2">
                        <p><em>Description</em>: {{ document.description }}</p><br/>
                        <p><em>Secret</em>: {{ document.is_secret }}</p><br/>
                        <a href="{{ document.file.url }}" download>
                            <button class="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-teal-300 to-lime-300 group-hover:from-teal-300 group-hover:to-lime-300 dark:text-white dark:hover:text-gray-900 focus:ring-4 focus:outline-none focus:ring-lime-200 dark:focus:ring-lime-800">
                                <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                                    Download
                                </span>
                            </button>
                        </a>
                    </div>
                </p>
                <p class="flex justify-end mr-4 sm:w-5/6 leading-relaxed text-lg font-medium mb-2">
                    <a href="{% url 'leads:document-update' document.pk %}">
                        <button class="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-cyan-500 to-blue-500 group-hover:from-cyan-500 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-cyan-200 dark:focus:ring-cyan-800">
                            <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                                Update
                            </span>
                        </button>
                    </a>
                    <a href="{% url 'leads:document-delete' document.pk %}">
                        <button class="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-cyan-500 to-blue-500 group-hover:from-cyan-500 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-cyan-200 dark:focus:ring-cyan-800">
                            <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                                Delete
                            </span>
                        </button>
                    </a>
                </p>

            </div>
        </div>
    </div>

{% endblock content %}

DjangoWebDev/IngotCRM/ingotcrm/templates/document_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="py-12 h-full bg-[#FCF1F1] dark:bg-[#474E68] px-2">
  <div class="flex justify-center">
    <p class="text-5xl text-extrabold mr-5 text-black dark:text-white">Documents</p>
  </div>

  <div class="flex mx-auto mb-2">
    {% if request.user.is_organisor %}
      <a  href="{% url 'leads:document-upload' %}"><button type="button" class="inline-block px-6 pt-2 pb-2 bg-blue-300 text-black font-medium text-xs leading-normal uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-400 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-400 active:shadow-lg hover:bg-yellow-200 transition duration-150 ease-in-out flex align-center">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 mr-2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m3.75 9v6m3-3H9m1.5-12H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
        </svg>
          Upload a new Document
      </button></a>
    {% endif %}
  </div>
  <hr/>

  <div class="flex grid grid-rows-4 grid-flow-col gap-4 py-6">
    <div class="row-span-2">
      <div class="xl:w-84">
          <form method="GET" action="{% url 'leads:document-list' %}" id='searchForm' class="text-center">
            <div class="grid grid-cols-4 py-4 gap-4 w-full bg-gray-200 border border-gray-200 rounded-lg shadow dark:bg-[#474E68] dark:border-gray-800">
              <div class="col-start-2 col-end-4 px-2">
                <label for="id_lead" class="text-black dark:text-white">Title, lead or filename contains</label>
                {{ form.title|as_crispy_field }}
              </div>

              <div class="col-start-2 col-end-4 px-2">
                <label for="id_date_added" class="text-black dark:text-white">Date added</label>
                {{ form.date_added|as_crispy_field }}
              </div>

              <div class="col-span-2 px-2">
                <label for="id_is_secret" class="text-black dark:text-white">Is secret</label>
                {{ form.is_secret|as_crispy_field }}
              </div>

              <p class="col-span-2 px-2">
                <input class="mt-3 rounded border-2 border-white px-6 py-2 text-xs font-medium uppercase dark:text-gray-200 transition duration-150 ease-in-out hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0" 
                type="submit" value="search" data-te-ripple-init>
              </p>
            </div>
          </form>
      </div>
    </div>



    <div class="flex justify-center row-span-4 col-span-4 mt-10">
      <ul role="list" class="p-6 divide-y divide-slate-200 mt-4">
        {% for document in documents %}
        <li class="flex py-4 first:pt-0 last:pb-0">
          <div class="ml-3 overflow-hidden">
            <p class="text-sm font-medium text-slate-900">
              <a href="{% url 'leads:document-detail' document.pk %}">
                <h3 class="text-2xl font-medium test-black dark:text-white">{{ document.title }}</h3>
              </a>
            </p>
            <p class="text-sm test-black dark:text-white truncate"><a href="{% url 'leads:lead-detail' document.lead.id %}">{{ document.lead }}</a> | {{ document.date_added }}</p>
          </div>
        </li>
        {% endfor %}
      <div class="flex justify-center pt-5">
        {% if is_paginated %}
          <nav aria-label="Page navigation example" onchange="location = finalurl();">
            <ul class="flex list-style-none">
              {% if page_obj.has_previous %}
                <li class="page-item relative block py-1.5 px-3 rounded border-0 bg-transparent outline-none transition-all duration-300 rounded text-gray-800 dark:text-gray-200 hover:text-gray-800 hover:bg-gray-200 focus:shadow-none">
                <a
                  data-page="{{page_obj.previous_page_number}}"
                  class="page-link"
                  href="{% url 'leads:document-list' %}?page={{ page_obj.previous_page_number }}">Previous</a></li>
              {% else %}
                <li class="page-item disabled  relative block py-1.5 px-3 rounded border-0 bg-transparent outline-none transition-all duration-300 rounded text-gray-500 dark:text-gray-200 pointer-events-none focus:shadow-none"><a
                  class="page-link"
                  href="#" tabindex="-1" aria-disabled="true">Previous</a></li>
              {% endif %}
              {% for page_num in paginator.page_range %}
                {% if page_num == page_obj.number %}
                <li class="page-item relative block py-1.5 px-3 border-2 border-color-cyan-900 bg-transparent outline-none transition-all duration-300 rounded text-blue-600 hover:bg-gray-200 focus:shadow-none">
                  <a
                    data-page="{{page_num}}"
                    class="page-link"
                    href="{% url 'leads:document-list' %}?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item relative block py-1.5 px-3 rounded border-0 bg-transparent outline-none transition-all duration-300 rounded text-gray-800 hover:text-gray-800 dark:text-gray-200 hover:bg-gray-200 focus:shadow-none">
                  <a
                    data-page="{{page_num}}"
                    class="page-link"
                    href="{% url 'leads:document-list' %}?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% endif %}
              {% endfor %}
              {% if page_obj.has_next %}
              <li class="page-item relative block py-1.5 px-3 rounded border-0 bg-transparent outline-none transition-all duration-300 rounded text-gray-800 hover:text-gray-800 dark:text-gray-200 hover:bg-gray-200 focus:shadow-none"><a
                  data-page="{{page_obj.next_page_number}}"
                  class="page-link"
                  href="{% url 'leads:document-list' %}?page={{ page_obj.next_page_number }}">Next</a></li>
              {% else %}
              <li class="page-item disabled relative block py-1.5 px-3 rounded border-0 bg-transparent outline-none transition-all duration-300 rounded text-gray-500 dark:text-gray-200 pointer-events-none focus:shadow-none"><a
                class="page-link"
                href="#" tabindex="-1" aria-disabled="true">Next</a></li>
              {% endif %}
            </ul>
          </nav>
          {% endif %}
        </div>
    </div>
  </div>
  
</div>
    
{% endblock content %}


{% block js %}
<script type="text/javascript">
	let searchForm = document.getElementById('searchForm')
	let pageLinks = document.getElementsByClassName('page-link')

	for(var i=0; pageLinks.length > i; i++){

		pageLinks[i].addEventListener('click', function(e){
			e.preventDefault()
			let page = this.dataset.page
			console.log('Page:', page)
			searchForm.innerHTML += `<input value="${page}" name="page" hidden >`
			searchForm.submit()
		})

	}
</script>
{% endblock js %}

DjangoWebDev/IngotCRM/ingotcrm/templates/document_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
  <h1 class="sm:text-3xl text-2xl font-extrabold mb-1 mt-5 text-center text-black dark:text-white border-b-2 border-gray-200 dark:border-green-200">
    Update the '<a href="{% url 'leads:document-detail' document.id %}" class="text-gray-700 dark:text-green-200 hover:text-cyan-600 dark:hover:text-cyan-400 hover:underline">{{ document.title }}</a>'
  </h1>

  <div class="flex justify-center text-center mt-6 px-2">
    <form method="post" enctype="multipart/form-data" autocomplete="off">
      {% csrf_token %}
      <div class="grid grid-cols-4 gap-4 w-full py-4 bg-gray-200 border border-gray-200 rounded-lg shadow dark:bg-[#474E68] dark:border-gray-800 text-black dark:text-white">
        <div class="col-span-4 px-2">
          <label for="id_lead" class="text-black dark:text-white">Lead</label>
          {{ form.lead|as_crispy_field }}
        </div>
        <div class="col-span-4 px-2">
          <label for="id_title" class="text-black dark:text-white">Title</label>
          {{ form.title|as_crispy_field }}
        </div>
        <div class="col-span-4 px-2">
          <label for="id_description" class="text-black dark:text-white">Description</label>
          {{ form.description|as_crispy_field }}
        </div>
        <div class="col-span-4 px-2">
          <label for="id_is_secret" class="text-black dark:text-white">Is secret</label>
          {{ form.is_secret|as_crispy_field }}
        </div>
        <div class="col-span-4 px-2">
          <label for="id_file" class="text-black dark:text-white">File</label>
          {{ form.file|as_crispy_field }}
        </div>

        <p class="col-start-2 col-end-4">
          <button type="submit" class="relative inline-flex items-center justify-center p-0.5 mt-2 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-green-400 to-blue-600 group-hover:from-green-400 group-hover:to-blue-600 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800">
            <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-gray-200 dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                Update
            </span>
          </button>
        </p>
      </div>
      <br/>
    </form>
  </div>
{% endblock content %}

DjangoWebDev/IngotCRM/ingotcrm/templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}"></script>