DjangoWebDev/DynamicFilter/core/urls.py
from django.urls import path
from .views import staticFilterView, dynamicFilterListView, landingView, BookListAPIView

app_name = "core"

urlpatterns = [
    path('', landingView, name="landing"),
    path('static_form/', staticFilterView, name="static-filter"),
    path('dynamic_form/', dynamicFilterListView.as_view(), name="dynamic-filter"),
    path('api/', BookListAPIView.as_view(), name="api-filter"),
]

DjangoWebDev/DynamicFilter/dynamicFilter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls", namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoWebDev/DynamicFilter/core/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name
    

class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Journal(models.Model):
    title = models.CharField(max_length=120)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category)
    publish_date = models.DateTimeField()
    views = models.IntegerField(default=0)
    reviewed = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Book(models.Model):
    class GenreChoices(models.TextChoices):
        FICTION = 'FIC'
        SCI_FI = 'SFI'
        FANTASY = 'FAN'
        MANGA = 'MAN'
        OTHER = 'OTH'
        HORROR = 'HOR'
        COMEDY = 'COM'
        DRAMA = 'DRA'
    
    title = models.CharField(max_length=128)
    price = models.FloatField()
    number_in_stock = models.PositiveIntegerField(default=0)
    genre = models.CharField(max_length=3, choices = GenreChoices.choices)
    author = models.ForeignKey("Author", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

DjangoWebDev/DynamicFilter/core/forms.py
from django import forms


class BookNameFilterForm(forms.Form):
    name = forms.CharField()

DjangoWebDev/DynamicFilter/core/views.py
from django.shortcuts import render
from django.db.models import Q
from django.views.generic import ListView
from rest_framework.generics import ListAPIView
from django_filters.rest_framework import DjangoFilterBackend

from .models import Journal, Category, Book
from .forms import BookNameFilterForm
from .filters import BookFilter
from .serializers import BookSerializer


class dynamicFilterListView(ListView):
    queryset = Book.objects.filter(number_in_stock__gt=0)
    template_name = 'dynamic_form.html'
    context_object_name = 'books'

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = BookFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.filterset.form
        return context


class BookListAPIView(ListAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer
    filter_backends = (DjangoFilterBackend, )
    filterset_class = BookFilter


# def dynamicFilterView(request):
#     book_filter = BookFilter(request.GET, queryset=Book.objects.all())

#     context = {
#         'form': book_filter.form,
#         'books': book_filter.qs,
#     }
#     return render(request, "dynamic_form.html", context)


def landingView(request):
    return render(request, "landing.html", {})


def is_valid_quertparam(param):
    return param != '' and param is not None


def staticFilterView(request):
    # Initial querysets
    qs = Journal.objects.all()
    categories = Category.objects.all()

    # Search bars
    title_contains_query = request.GET.get("title_contains")
    title_exact_query = request.GET.get("title_exact")
    title_or_author_query = request.GET.get("title_or_author")

    # Filters
    view_count_min = request.GET.get("view_count_min")
    view_count_max = request.GET.get("view_count_max")
    date_min = request.GET.get("date_min")
    date_max = request.GET.get("date_max")
    category = request.GET.get("category")
    reviewed = request.GET.get("reviewed")
    not_reviewed = request.GET.get("not_reviewed")

    # Filtering
    if is_valid_quertparam(title_contains_query):
        qs = qs.filter(title__icontains=title_contains_query)
    elif is_valid_quertparam(title_exact_query):
        qs = qs.filter(title__iexact=title_exact_query)
    elif is_valid_quertparam(title_or_author_query):
        qs = qs.filter(Q(title__icontains=title_or_author_query) | Q(author__name__icontains=title_or_author_query)).distinct()

    if is_valid_quertparam(view_count_min):
        qs = qs.filter(views__gte=view_count_min)
    
    if is_valid_quertparam(view_count_max):
        qs = qs.filter(views__lt=view_count_max)
    
    if is_valid_quertparam(date_min):
        qs = qs.filter(publish_date__gte=date_min)
    
    if is_valid_quertparam(date_max):
        qs = qs.filter(publish_date__lt=date_max)
    
    if is_valid_quertparam(category) and category != "Choose...":
        qs = qs.filter(categories__name=category)
    
    if reviewed == "on":
        qs = qs.filter(reviewed=True)
    elif not_reviewed == "on":
        qs = qs.filter(reviewed=False)
    
    # Context
    context = {
        'queryset': qs,
        'categories': categories
    }
    
    return render(request, "static_form.html", context)

DjangoWebDev/DynamicFilter/core/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <title>Filters</title>

        <!-- Bootstrap CDN -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        
        <!-- Font-awesome CDN -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" rel="stylesheet" type="text/css">

    </head>

    <body class="h-80">
        <!-- Header -->
        {% include 'navbar.html' %}

        <!-- Content -->
        {% block content %}
        {% endblock content %}

        <!-- JavaScript -->
        {% block js %}
        {% endblock js %}

        <!-- Footer -->
        {% include 'footer.html' %}
    </body>
</html>

DjangoWebDev/DynamicFilter/core/templates/dynamic_form.html
{% extends "base.html" %}

{% block content %}
    <!-- Page content -->
    <h2 class="d-flex justify-content-center">
        <strong>Dynamic filter</strong>
    </h2>
    
    <div class="container mb-2">
        <div class="row">
            
            <form method="GET" class="mb-4" action="{% url 'core:dynamic-filter' %}">
                {{ form.as_p }}
                <input type="submit" value="Submit" class="btn btn-primary" />
            </form>

            <hr/>
            {% for book in books %}
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">"{{ book.title }}"</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ book.author }}</h6>
                        <p class="card-text">Genre: {{ book.get_genre_display }}</p>
                        <p class="card-text">Price: {{ book.price }}</p>
                        <p class="card-text text-muted">In stock: {{ book.number_in_stock }}</p>
                        <a href="#" class="card-link">See more</a>
                    </div>
                </div>
            {% endfor %}
            
        </div>
    </div>
{% endblock %}

DjangoWebDev/DynamicFilter/core/templates/footer.html
<footer class="footer mt-auto py-3 bg-light">
    <!-- Section: Links  -->
    <section class="d-flex justify-content-end ">
        <div class="container text-center">
            <!-- Grid row -->
            <div class="row mt-3">
                <h6 class="text-uppercase fw-bold mb-2">Contact</h6>
                    <p>
                        <!-- Github -->
                        <a class="btn btn-outline-light btn-floating m-1 ml-4" href="https://github.com/Nar0kan?tab=repositories" role="button">
                            <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" width="24" height="24">
                                <title>GitHUB</title>
                                <path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/>
                            </svg>
                        </a>

                        <!-- Linkedin -->
                        <a class="btn btn-outline-light btn-floating m-1 ml-4" href="https://www.linkedin.com/in/nikita-kirichenko-781062251/" role="button">
                            <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" width="24" height="24">
                                <title>LinkedIn</title>
                                <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
                            </svg>
                        </a>
                        <h6 class="fas fa-envelope me-1 px-2">nick.kirichenko.dev@gmail.com</h6>
                        
                        <h6 class="fas fa-envelope me-1 px-2">wertynhard@gmail.com</h6>
                        
                    </p>
                </div>
            </div>
    </section>
</footer>

DjangoWebDev/DynamicFilter/core/templates/landing.html
{% extends "base.html" %}

DjangoWebDev/DynamicFilter/core/templates/navbar.html
<header>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'core:landing' %}">
                Filters
            </a>
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'core:static-filter' %}">Static</a>
                </li>
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'core:dynamic-filter' %}">Dynamic</a>
                </li>
            </div>
        </div>
    </nav>
</header>

DjangoWebDev/DynamicFilter/core/templates/static_form.html
{% extends "base.html" %}

{% block content %}
    <!-- Page content -->
    <h2 class="d-flex justify-content-center">
        <strong>Static filter</strong>
    </h2>
    
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <form method="GET" action=".">
                    <div class="form-row">
                        <div class="form-group mb-2">
                            <div class="input-group">
                                <input class="form-control py-2 border-right-0 border" type="search" name="title_contains" placeholder="Title contains...">
                                <button type="submit" class="pt-1 form-submit border-right-2 border border-yellow">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" width="32" height="32">
                                        <path fill-rule="evenodd" d="M10.5 3.75a6.75 6.75 0 100 13.5 6.75 6.75 0 000-13.5zM2.25 10.5a8.25 8.25 0 1114.59 5.28l4.69 4.69a.75.75 0 11-1.06 1.06l-4.69-4.69A8.25 8.25 0 012.25 10.5z" clip-rule="evenodd" />
                                    </svg>
                                </button>
                            </div>
                        </div>
                        <div class="form-group mb-2">
                            <div class="input-group">
                                <input class="form-control py-2 border-right-0 border" type="search" name="title_exact" placeholder="Title exact...">
                                <button type="submit" class="pt-1 form-submit border-right-2 border border-yellow">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" width="32" height="32">
                                        <path fill-rule="evenodd" d="M10.5 3.75a6.75 6.75 0 100 13.5 6.75 6.75 0 000-13.5zM2.25 10.5a8.25 8.25 0 1114.59 5.28l4.69 4.69a.75.75 0 11-1.06 1.06l-4.69-4.69A8.25 8.25 0 012.25 10.5z" clip-rule="evenodd" />
                                    </svg>
                                </button>
                            </div>
                        </div>
                        <div class="form-group mb-2">
                            <div class="input-group">
                                <input class="form-control py-2 border-right-0 border" type="search" name="title_or_author" placeholder="Title or author...">
                                <button type="submit" class="pt-1 form-submit border-right-2 border border-yellow">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" width="32" height="32">
                                        <path fill-rule="evenodd" d="M10.5 3.75a6.75 6.75 0 100 13.5 6.75 6.75 0 000-13.5zM2.25 10.5a8.25 8.25 0 1114.59 5.28l4.69 4.69a.75.75 0 11-1.06 1.06l-4.69-4.69A8.25 8.25 0 012.25 10.5z" clip-rule="evenodd" />
                                    </svg>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex justify-content-between mb-2">
                        <div class="form-group col-md-2 col-lg-2">
                            <label for="viewCountMin" class="form-label">Minimum View Count</label>
                            <input type="number" min=0 class="form-control" id="viewCountMin" name="view_count_min" placeholder="0">
                        </div>
                        <div class="form-group col-md-2 col-lg-2">
                            <label for="viewCountMax" class="form-label">Maximum View Count</label>
                            <input type="number" min=0 class="form-control" id="viewCountMax" name="view_count_max" placeholder="1000000">
                        </div>
                        <div class="form-group col-md-2 col-lg-2">
                            <label for="publishDateMin" class="form-label">Publish date minimum</label>
                            <input type="date" class="form-control" id="publishDateMin" name="date_min">
                        </div>
                        <div class="form-group col-md-2 col-lg-2">
                            <label for="publishDateMax" class="form-label">Publish date maximum</label>
                            <input type="date" class="form-control" id="publishDateMax" name="date_max">
                        </div>
                    </div>
                    <div class="d-flex justify-content-between mb-2">
                        <div class="form-group col-md-2 col-lg-2">
                            <label for="category" class="form-label">Category</label>
                            <select id="category" class="form-select" name="category">
                            <option selected>Choose...</option>
                            {% for category in categories %}
                                <option>{{ category.name }}</option>
                            {% endfor %}
                            </select>
                        </div>
                        <div class="form-group col-md-2 col-lg-2">
                            <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="reviewed" name="reviewed">
                            <label class="form-check-label" for="reviewed">
                                Reviewed
                            </label>
                            </div>
                            <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="not_reviewed" name="not_reviewed">
                            <label class="form-check-label" for="not_reviewed">
                                Not reviewed
                            </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-md-2 col-lg-2">
                        <button type="submit" class="btn btn-primary">Search</button>
                    </div>
                </form>
            </div>
        
            <div class="col-sm">
                <ul>
                    {% for journal in queryset %}
                        <li class="border-right-2 border-color-yellow border">
                            <h2>"{{ journal.title }}"<h2>
                            <span>Author: {{ journal.author }}</span>
                            <span>
                                {% for category in journal.categories.all %}
                                    {{ category }}
                                {% endfor %}
                            </span>
                            <span>Publish date: {{ journal.publish_date }}</span>
                            <span>View count: {{ journal.views }}</span>
                            <span>Reviewed: {{ journal.reviewed }}</span>
                        
                        </li><br/>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}